### ISSUE TITLE
Not compile grid gutter to css if it equal 0

### ISSUE THREAD

**Issue by gotbahn** [gotbahn/flex-box-grid#1]

**Comment by godban** [comment]
Not include offsets

**Comment by MarcelHekkert** [comment]
To make the padding on the .container class is working fine, make sure the following css is available and it will all work fine!

```
*,
*:after,
*:before {
    box-sizing: inherit;
}

html {
    box-sizing: border-box;
}
```

**Comment by godban** [comment]
@MarcelHekkert, thx for suggestion
here I just note for future releases to not include unnecessary css output
